# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: CI

# This determines when this workflow is run
on:
  push:
    branches: [ros2]
  pull_request:
    branches: [ros2]
  workflow_dispatch: {}

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: jazzy, ROS_REPO: testing, DOCKER_IMAGE: "ghcr.io/sloretz/ros:jazzy-perception", ALLOW_FAIL: no}
          - {ROS_DISTRO: kilted, ROS_REPO: testing, DOCKER_IMAGE: "ghcr.io/sloretz/ros:kilted-perception", ALLOW_FAIL: no}
          - {ROS_DISTRO: rolling, ROS_REPO: testing, DOCKER_IMAGE: "ghcr.io/sloretz/ros:rolling-perception", ALLOW_FAIL: yes}
        os: ["ubuntu-24.04", "ubuntu-24.04-arm"]
    name: "${{ matrix.env.ROS_DISTRO }}-${{ matrix.os }}"
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache # Directory for ccache (and how we enable ccache in industrial_ci)
      AFTER_SETUP_TARGET_WORKSPACE: 'cd $BASEDIR/target_ws/src/ros-utils; for d in *; do if [[ "$d" != "cras_lint" ]] && [[ "$d" != "cras_cpp_common" ]] && [[ "$d" != "cras_topic_tools" ]]; then rm -rf "$d"; fi; done'
      UPSTREAM_WORKSPACE: .github/ci.ros2.rosinstall
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      # This step will fetch/store the directory used by ccache before/after the ci run
      - name: Cache ccache
        uses: rhaschke/cache@main
        continue-on-error: ${{ matrix.env.ALLOW_FAIL }}
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.os }}-${{ matrix.env.ROS_DISTRO }}-${{ matrix.env.ROS_REPO }}-${{ github.sha }}-${{ github.run_id }}
          restore-keys: |
            ccache-${{ matrix.os }}-${{ matrix.env.ROS_DISTRO }}-${{ matrix.env.ROS_REPO }}-${{ github.sha }}
            ccache-${{ matrix.os }}-${{ matrix.env.ROS_DISTRO }}
        env:
          GHA_CACHE_SAVE: always
      # Run industrial_ci
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}
